tasks:
  - name: Dependencies
    before: echo "Setting up dev enviroment."
    init: |
      npm install
    # npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
    # npm run dev
    command: echo "Done!"
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
  # QoL
  - CoenraadS.bracket-pair-colorizer-2
  - jerrygoyal.shortcut-menu-bar
  - EditorConfig.EditorConfig
  - ms-vscode.sublime-keybindings
  - dbaeumer.vscode-eslint
  - HookyQR.beautify
  - esbenp.prettier-vscode
  - oouo-diogo-perdigao.docthis
  - eamodio.gitlens
  - GitHub.vscode-pull-request-github
  - eg2.vscode-npm-script
  # Dev
  - svelte.svelte-vscode
  - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/astro-build/vsextensions/astro-vscode/0.7.7/vspackage
  - bradlc.vscode-tailwindcss
  - gencer.html-slim-scss-css-class-completion
  - ms-azuretools.vscode-docker
  # - DotJoshJohnson.xml
  # - address.vsix